### ISSUE TITLE
sol_num??

### ISSUE THREAD

**Issue by prutsky** [TontonTremblay/Machine_Learning#1]
Hi,
I found this code and try to use it to solve a different magic puzzle.

When I run the program I get 1 solution: 861812

You write that there are 2 solutions to your puzzle, why does it only return 1?

Second question. How should I read this number, so I can arrange the card in the correct order. I would expect a 9 digit number and nu double numbers (like 8 en 1 in your solution). I don't understand it...
Thx,
Erwin

**Comment by TontonTremblay** [comment]
I have not touched this code in a while. But I remember that I did not write the code in a way that it can deal with rotation, e.g. it recognizes a board configuration as a rotation of an other. If you want to read the solution, you need to execute line 179 to 184. There you will get a hard to read solution: 
```
2 pin a , 7 pin a , 4 yel f ,
6 red a , 8 yel a , 5 yel f ,
3 pin a , 1 yel a , 9 gre f ,
``` 
This reads, put card 2 top left with ass pink north, then put id 7 with pink ass north, etc. The colour and type of face is always north.

Here is how you find the ids:
```
# Direction position array: W,N,E,S
# Colour, r = 0, y = 1, g = 2, p = 3
# ass = 0, front = 1
# first is colour, piece
# ass as to front with colour
c = [[1,[(1,0),(3,1),(2,1),(0,0)]],
     [2,[(2,0),(0,1),(1,1),(3,0)]],
     [3,[(0,1),(2,1),(0,0),(3,0)]],
     [4,[(3,0),(1,0),(0,1),(1,1)]],
     [5,[(0,0),(2,0),(3,1),(1,1)]],
     [6,[(2,1),(0,0),(2,0),(3,1)]],
     [7,[(0,0),(1,1),(2,1),(3,0)]],
     [8,[(3,0),(1,1),(2,1),(1,0)]],
     [9,[(1,1),(1,0),(3,0),(2,1)]]]
```
So an array entry reads as follow: 
[ID,[face west : (colour id, face or ass),face north : (colour id, face or ass) ...] 
I think with that you can read the output. 

PS if you let the code run, you will get a lot of interesting results from rotations being not taken into consideration. This code is not meant to be robust, it is supposed to run and find one solution and I stumble on two solutions by chance.
